version: "3.9"

services:
    app:
        build: .
        command: npm start
        volumes:
            - app_data:/usr/src/app/
        ports:
            - 3333:3333
        env_file:
            - ./.env

volumes:
    app_data:
